# Generated by Django 4.1.7 on 2023-05-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='is_request',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
