# Generated by Django 4.1.7 on 2023-05-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friend_is_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='is_request',
        ),
    ]
