# Generated by Django 4.1.7 on 2023-05-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_friend_is_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_request',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
